#!/usr/bin/env bash
# Session definition for a GPU pod session. Single source of truth: every other
# script in scripts/pod/ sources this file instead of hardcoding a run name,
# config, checkpoint or HF path.
#
# SESSION: Experiment 1 — recovery-data scaling (logs/PROPOSAL.md §4).
# 24 arms = 6 rungs x 2 seeds x 2 inits, trained on the uniform token-ladder cut.
#
# The session runs on TWO pods, split by initialization so that losing a pod
# costs one init axis rather than half of every curve. POD_ROLE selects the
# slice and must be exported before this file is sourced:
#
#   POD_ROLE=pca   -> the 12 PCA/sandwich-init arms
#   POD_ROLE=rand  -> the 12 random-baseline-init arms
#
# Arms are ordered seed a first, then seed b, and small rungs first. If the
# budget deadline cuts a pod short, what is lost is the tail of the second seed,
# not a whole curve.

SESSION=e1_scaling
SESSION_DATE=20260801
POD_ROLE=${POD_ROLE:-pca}

# Arm entries are name|config|final-step-tag, generated by
# scripts/data/build_experiment1_configs.py. An arm differs from
# configs/stage3/recovery.json only in data source, rung, seed and student_path.
ARMS_PCA=(
  "e1_r0250k_sa_pca|configs/stage3/e1/e1_r0250k_sa_pca.json|step_000324"
  "e1_r0460k_sa_pca|configs/stage3/e1/e1_r0460k_sa_pca.json|step_000570"
  "e1_r0860k_sa_pca|configs/stage3/e1/e1_r0860k_sa_pca.json|step_001023"
  "e1_r1600k_sa_pca|configs/stage3/e1/e1_r1600k_sa_pca.json|step_001761"
  "e1_r2960k_sa_pca|configs/stage3/e1/e1_r2960k_sa_pca.json|step_002916"
  "e1_r5500k_sa_pca|configs/stage3/e1/e1_r5500k_sa_pca.json|step_004412"
  "e1_r0250k_sb_pca|configs/stage3/e1/e1_r0250k_sb_pca.json|step_000324"
  "e1_r0460k_sb_pca|configs/stage3/e1/e1_r0460k_sb_pca.json|step_000570"
  "e1_r0860k_sb_pca|configs/stage3/e1/e1_r0860k_sb_pca.json|step_001023"
  "e1_r1600k_sb_pca|configs/stage3/e1/e1_r1600k_sb_pca.json|step_001761"
  "e1_r2960k_sb_pca|configs/stage3/e1/e1_r2960k_sb_pca.json|step_002916"
  "e1_r5500k_sb_pca|configs/stage3/e1/e1_r5500k_sb_pca.json|step_004412"
)
ARMS_RAND=(
  "e1_r0250k_sa_rand|configs/stage3/e1/e1_r0250k_sa_rand.json|step_000324"
  "e1_r0460k_sa_rand|configs/stage3/e1/e1_r0460k_sa_rand.json|step_000570"
  "e1_r0860k_sa_rand|configs/stage3/e1/e1_r0860k_sa_rand.json|step_001023"
  "e1_r1600k_sa_rand|configs/stage3/e1/e1_r1600k_sa_rand.json|step_001761"
  "e1_r2960k_sa_rand|configs/stage3/e1/e1_r2960k_sa_rand.json|step_002916"
  "e1_r5500k_sa_rand|configs/stage3/e1/e1_r5500k_sa_rand.json|step_004412"
  "e1_r0250k_sb_rand|configs/stage3/e1/e1_r0250k_sb_rand.json|step_000324"
  "e1_r0460k_sb_rand|configs/stage3/e1/e1_r0460k_sb_rand.json|step_000570"
  "e1_r0860k_sb_rand|configs/stage3/e1/e1_r0860k_sb_rand.json|step_001023"
  "e1_r1600k_sb_rand|configs/stage3/e1/e1_r1600k_sb_rand.json|step_001761"
  "e1_r2960k_sb_rand|configs/stage3/e1/e1_r2960k_sb_rand.json|step_002916"
  "e1_r5500k_sb_rand|configs/stage3/e1/e1_r5500k_sb_rand.json|step_004412"
)
if [ "$POD_ROLE" = "rand" ]; then ARMS=("${ARMS_RAND[@]}"); else ARMS=("${ARMS_PCA[@]}"); fi

# Reference checkpoints scored on the same GPU before training, so every arm has
# a same-device baseline. Format: hf-glob|local-dest|revision|scorecard-name.
# Both Stage 1 inits are staged (an arm's student_path must exist), but only the
# pod's own init is scored — the step-0 point of the curve it is measuring.
# Both are staged on both pods — hashes_ckpt.txt covers both, and a missing file
# fails the manifest check. An empty 4th field means "stage but do not score",
# which both score_refs.sh and the orchestrator honour.
REF_CKPTS_PCA=(
  "stage1/qwen3_0p6b_init_v0/checkpoint|artifacts/stage1/qwen3_0p6b_init_v0/checkpoint|main|stage1_init_v0_step0"
  "stage1/qwen3_0p6b_init_v0/random_baseline|artifacts/stage1/qwen3_0p6b_init_v0/random_baseline|main|"
)
REF_CKPTS_RAND=(
  "stage1/qwen3_0p6b_init_v0/random_baseline|artifacts/stage1/qwen3_0p6b_init_v0/random_baseline|main|stage1_random_step0"
  "stage1/qwen3_0p6b_init_v0/checkpoint|artifacts/stage1/qwen3_0p6b_init_v0/checkpoint|main|"
)
if [ "$POD_ROLE" = "rand" ]; then
  REF_CKPTS=("${REF_CKPTS_RAND[@]}")
else
  REF_CKPTS=("${REF_CKPTS_PCA[@]}")
fi

# Transfer artifacts on the private HF relay (staged from the dev box).
HF_REPO=AlphaAvatar/aadistill-artifacts
TRANSFER_BUNDLE=transfer/repo_20260801.bundle
TRANSFER_DATA=transfer/stage2_data_20260726.tar.zst
TRANSFER_EXTRA=
EXTRA_EXPECT=

# The packed token ladder Experiment 1 trains on. Small (20 MB) and pulled
# straight from the relay rather than tarred into the transfer bundle, because
# it is the experiment's data identity and must arrive hash-checked.
LADDER_PREFIX=stage3_recovery_corpus_v2/ladder_uniform
LADDER_DEST=artifacts/stage3/ladder_uniform

# Must be exported: verify_and_report.py reads it from the environment, and a
# non-exported value made a whole session fail upload verification against a
# path nothing had written to.
export HF_PREFIX_BASE=e1_scaling_20260801

# Pre-registered abort rule (logs/PROPOSAL.md §7): stop an arm whose primary-val
# CE at the first eval exceeds its step-0 value, rather than retuning mid-session.
ABORT_ARMS=""
ABORT_CHECK_STEP=25

# --- budget guard (AGENTS.md P6/P12) --------------------------------------
# The session is capped at $60 total across both pods. A pod is created with a
# hard --terminate-after at POD_DEADLINE_HOURS so the cap holds even if every
# other guard fails: 2 pods x 30.0 h x $0.99/h = $59.40.
#
# The orchestrator additionally refuses to *start* an arm it cannot finish
# before the deadline, so a cut session ends with completed uploads rather than
# a pod killed mid-transfer.
POD_DEADLINE_HOURS=30.0
HOURLY_USD=0.99
SECONDS_PER_STEP=4.3          # measured, block_len 8192 + gradient checkpointing
POST_RUN_RESERVE_MIN=25       # evals + hashing + upload for one arm

SESSION_COMMIT_SUBJECT="stage3: ${SESSION} session — logs"
SESSION_COMMIT_BODY=""

# Left EMPTY on purpose — verify_and_report.py is verify-only, and a session
# must supply its own write-up rather than inherit another experiment's rules.
REPORT_CMD=

# Paths setup.sh checks exist after the bundle + data land.
HOLDOUT=data/warmup/holdout_v1.jsonl
BEHAVIOR_PROMPTS=data/eval_behavior_v0/prompts.jsonl
# Formal behaviour measurement is UNRESTRICTED (AGENTS.md P18). This value is
# used only for cheap smoke checks and is recorded as a censored measurement.
BEHAVIOR_MAX_NEW_TOKENS=512

# Files this session's post_run.sh writes per arm; the orchestrator fetches
# exactly these. Experiment 1 drops the INT8, probe and capped-behaviour
# artifacts — see the header of post_run.sh for why.
ARM_ARTIFACTS="train_log.jsonl run_manifest.json eval_holdout_v1.json gen_smoke.json console.log"

# Convenience accessors -------------------------------------------------------
arm_field() { printf '%s' "$1" | cut -d'|' -f"$2"; }
arm_names() { local a; for a in "${ARMS[@]}"; do arm_field "$a" 1; done; }
