"""Enumerate artifacts in Python, and refuse teardown until they are safe here.

E6b lost its structured training logs to a bundling step that listed
`artifacts/audit/three_mode` and two JSON files — the set E6 needed — and never
listed `artifacts/stage3/e6b_*/train_log.jsonl`, because the launcher was derived
from E6, which did not train. `tar` bundled what it was given, exited 0, the
digest matched, the transfer verified, and the pod was deleted. Every check
passed. None of them was "is everything that had to survive actually here".

The related fragility is `$(ls -d …)` inside a nested ssh string: the glob is
expanded by the remote login shell, and when it matches nothing the substitution
is empty and `tar` silently bundles a smaller set. Three launchers still carry
that construct (E3, E4, E5 — frozen records of completed runs). It is banned
going forward, and this module is the replacement.

The design is one idea: **an explicit, declared manifest is the unit of
collection**, generated by Python that can fail loudly, and the archive is built
*from* that manifest rather than from a glob evaluated somewhere else. A path
that should exist and does not is a manifest error before any tar runs, at a
point in the session where the pod is still alive and the file can still be
found.

`evaluate_teardown` then gates deletion behind the ordered checklist. A missing
required artifact blocks normal teardown; only the independent cost watchdog may
override, and only with a recorded reason.
"""

from __future__ import annotations

import hashlib
import json
import tarfile
import time
from dataclasses import dataclass, asdict, field
from pathlib import Path

from .manifest import sha256_file


class ArtifactError(RuntimeError):
    """A required artifact class is missing or unusable."""


# Two different claims a manifest can make about a file, and they must never be
# confused. The 2026-08-09 canary made the bounded-read fix necessary; this makes
# it safe.
#
# `mutable_snapshot`  the writer may still be active. The archive records the
#                     exact byte boundary it captured and hashes those bytes.
#                     It proves **already-emitted data is durable**. It does not
#                     claim the file is complete, and it must not be accepted as
#                     a finished artifact.
# `final_required`    the producing process has finished, its terminal marker
#                     exists, and the file is quiescent. Only then is a manifest
#                     entry a claim about a *complete* artifact.
#
# `final_required` is the default, deliberately: a spec written without thinking
# about it gets the strict reading, and a bounded prefix of a still-growing file
# can never satisfy a normal teardown by accident.
LIFECYCLES = ("final_required", "mutable_snapshot")


@dataclass(frozen=True)
class CompletionMarker:
    """Evidence that the process producing an artifact has actually finished."""

    path: str
    contains: str

    def satisfied(self, root: Path) -> tuple[bool, str]:
        p = root / self.path
        if not p.is_file():
            return False, f"{self.path} does not exist"
        text = p.read_text(errors="replace")
        if self.contains not in text:
            return False, f"{self.path} does not contain {self.contains!r}"
        return True, ""

    def as_dict(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class ArtifactSpec:
    """One declared artifact class and the paths that must satisfy it.

    `pattern` is expanded by Python's `glob`, relative to the manifest root —
    never by a remote shell inside a quoted ssh command.

    `lifecycle` says what a matching file *means*: see `LIFECYCLES`.
    """

    artifact_class: str
    pattern: str
    required: bool = True
    min_matches: int = 1
    min_bytes: int = 1
    lifecycle: str = "final_required"

    def __post_init__(self) -> None:
        if self.lifecycle not in LIFECYCLES:
            raise ArtifactError(
                f"lifecycle must be one of {LIFECYCLES}, got "
                f"{self.lifecycle!r}")

    def as_dict(self) -> dict:
        return asdict(self)


# The classes a training session must bring home. `event_stream` is first and
# required because it is the one E6b lost, and because it is the only artifact
# here that cannot be reconstructed from anything else: checkpoints can be
# re-evaluated, generations are re-scoreable, console logs can be parsed, but a
# destroyed jsonl event stream is simply gone.
def training_session_specs(run_globs: tuple[str, ...]) -> tuple[ArtifactSpec, ...]:
    specs: list[ArtifactSpec] = []
    for g in run_globs:
        specs += [
            ArtifactSpec("event_stream", f"{g}/train_log.jsonl"),
            ArtifactSpec("run_manifest", f"{g}/run_manifest*.json"),
        ]
    return tuple(specs)


@dataclass
class ManifestEntry:
    path: str
    artifact_class: str
    size_bytes: int
    sha256: str
    lifecycle: str = "final_required"


@dataclass
class ArtifactManifest:
    root: str
    entries: list[ManifestEntry] = field(default_factory=list)
    specs: list[dict] = field(default_factory=list)
    missing: list[dict] = field(default_factory=list)
    created_utc: str = ""
    # Files that grew between manifest and archive, recorded rather than
    # silently absorbed: it is normal for an append-only training log and it is
    # a red flag for anything else.
    appended_during_archive: list[dict] = field(default_factory=list)
    completion_markers: list[dict] = field(default_factory=list)
    completion_marker_failures: list[str] = field(default_factory=list)
    still_being_written: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.missing

    @property
    def final_streams_quiescent(self) -> bool:
        """Every `final_required` class is complete, settled and marker-backed.

        Separate from `ok` because they answer different questions. `ok` asks
        "is everything here"; this asks "is what is here *finished*". A bounded
        prefix of a growing log can make the first true and must never make the
        second true.
        """
        if self.completion_marker_failures or self.still_being_written:
            return False
        return not any(m.get("lifecycle", "final_required") == "final_required"
                       for m in self.missing)

    def snapshot_entries(self) -> list[ManifestEntry]:
        return [e for e in self.entries if e.lifecycle == "mutable_snapshot"]

    def final_entries(self) -> list[ManifestEntry]:
        return [e for e in self.entries if e.lifecycle == "final_required"]

    def paths(self) -> list[str]:
        return [e.path for e in self.entries]

    def by_class(self, artifact_class: str) -> list[ManifestEntry]:
        return [e for e in self.entries if e.artifact_class == artifact_class]

    def as_dict(self) -> dict:
        return {
            "root": self.root,
            "created_utc": self.created_utc,
            "ok": self.ok,
            "specs": self.specs,
            "entries": [asdict(e) for e in self.entries],
            "missing": self.missing,
            "appended_during_archive": self.appended_during_archive,
            "completion_markers": self.completion_markers,
            "completion_marker_failures": self.completion_marker_failures,
            "still_being_written": self.still_being_written,
            "final_streams_quiescent": self.final_streams_quiescent,
        }

    def write(self, path: str | Path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.as_dict(), indent=2) + "\n")
        return path

    @classmethod
    def load(cls, path: str | Path) -> "ArtifactManifest":
        d = json.loads(Path(path).read_text())
        return cls(
            root=d["root"],
            entries=[ManifestEntry(**e) for e in d["entries"]],
            specs=d.get("specs", []),
            missing=d.get("missing", []),
            created_utc=d.get("created_utc", ""),
            appended_during_archive=d.get("appended_during_archive", []),
            completion_markers=d.get("completion_markers", []),
            completion_marker_failures=d.get("completion_marker_failures", []),
            still_being_written=d.get("still_being_written", []),
        )


def _fingerprint(p: Path) -> tuple[int, float]:
    st = p.stat()
    return st.st_size, st.st_mtime


def build_manifest(root: str | Path, specs: tuple[ArtifactSpec, ...], *,
                   created_utc: str = "", settle_seconds: float = 0.0,
                   completion_markers: tuple[CompletionMarker, ...] = (),
                   sleep=time.sleep) -> ArtifactManifest:
    """Expand every spec against the filesystem and hash what is there.

    Does not raise on a missing required artifact: it records it in `missing`
    and leaves `ok` False. The caller decides — on the pod, mid-session, with
    the files still reachable — whether to hunt for it or to accept the loss
    knowingly. Raising here would only turn a recoverable gap into a crashed
    collection step.

    **`final_required` classes are held to two extra conditions**, because the
    bounded-read archive makes a growing file *archivable* and that must not make
    it *acceptable*:

    * every `completion_marker` must be present and carry its expected content —
      evidence the producing process actually finished, not merely that a file
      exists;
    * the file must be **quiescent**: size and mtime unchanged across a
      `settle_seconds` window. A file that is still growing is recorded as
      missing with reason `still being written`, so it can never satisfy a
      normal teardown.

    `mutable_snapshot` classes skip both. That is their whole point: they claim
    "these bytes are durable", not "this file is finished".
    """
    root = Path(root)
    manifest = ArtifactManifest(root=str(root), created_utc=created_utc,
                                specs=[s.as_dict() for s in specs])
    manifest.completion_markers = [m.as_dict() for m in completion_markers]

    marker_failures = []
    if any(s.lifecycle == "final_required" and s.required for s in specs):
        for marker in completion_markers:
            ok, why = marker.satisfied(root)
            if not ok:
                marker_failures.append(why)
    manifest.completion_marker_failures = marker_failures

    seen: set[str] = set()
    for spec in specs:
        matches = sorted(p for p in root.glob(spec.pattern) if p.is_file())
        usable = [p for p in matches if p.stat().st_size >= spec.min_bytes]

        growing: list[str] = []
        if spec.lifecycle == "final_required" and usable and settle_seconds > 0:
            before = {p: _fingerprint(p) for p in usable}
            sleep(settle_seconds)
            for p in list(usable):
                if not p.is_file() or _fingerprint(p) != before[p]:
                    growing.append(str(p.relative_to(root)))
                    usable.remove(p)
        if growing:
            manifest.still_being_written.extend(growing)

        blocked = spec.lifecycle == "final_required" and marker_failures
        if spec.required and (len(usable) < spec.min_matches or blocked):
            if blocked:
                reason = ("the producing process has not signalled completion: "
                          + "; ".join(marker_failures))
            elif growing:
                reason = (f"still being written ({', '.join(growing)}); a "
                          "bounded prefix of a growing file is a snapshot, not "
                          "a final artifact")
            elif not matches:
                reason = "no file matched the pattern"
            else:
                reason = (f"{len(matches) - len(usable)} match(es) below "
                          f"{spec.min_bytes} bytes")
            manifest.missing.append({
                "artifact_class": spec.artifact_class,
                "pattern": spec.pattern,
                "lifecycle": spec.lifecycle,
                "matches": len(matches),
                "usable_matches": len(usable),
                "min_matches": spec.min_matches,
                "reason": reason,
            })
        for p in usable:
            rel = str(p.relative_to(root))
            if rel in seen:
                continue
            seen.add(rel)
            manifest.entries.append(ManifestEntry(
                path=rel, artifact_class=spec.artifact_class,
                size_bytes=p.stat().st_size, sha256=sha256_file(p),
                lifecycle=spec.lifecycle))
    return manifest


class _HashingLimitedReader:
    """Feed tar exactly `limit` bytes, hashing them on the way through."""

    def __init__(self, fh, limit: int):
        self._fh = fh
        self._left = limit
        self.digest = hashlib.sha256()

    def read(self, size: int = -1) -> bytes:
        if self._left <= 0:
            return b""
        want = self._left if size is None or size < 0 else min(size, self._left)
        chunk = self._fh.read(want)
        self._left -= len(chunk)
        self.digest.update(chunk)
        return chunk


def create_archive(manifest: ArtifactManifest, out_path: str | Path) -> Path:
    """Archive exactly the manifest's files, and make the manifest describe what
    was actually archived.

    A path in the manifest that has vanished is an error, not a silently smaller
    tarball — that difference is the entire E6b artifact loss.

    **The manifest is rewritten in place to the archived bytes**, and that is not
    a convenience. `train_log.jsonl` is appended by the trainer for the whole
    run, so between `build_manifest` hashing it and `tar` reading it, it grows.
    The live canary on 2026-08-09 caught exactly this: 2,166 bytes at manifest
    time, 2,230 in the archive, one event written in the gap — and the teardown
    gate then blocked forever on `archive_contents_verified`, because the
    manifest described bytes that no longer existed anywhere.

    So each file is read **once**, capped at the size observed when it is
    opened, hashed as it streams into the tar, and the entry updated to those
    exact bytes. For an append-only jsonl a size-capped read is a valid prefix
    (a torn final line is already tolerated by the relay's reader). A file that
    has *shrunk* is an error — that is truncation, not appending.
    """
    root = Path(manifest.root)
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    grew: list[dict] = []
    with tarfile.open(out_path, "w:gz") as tar:
        for entry in manifest.entries:
            src = root / entry.path
            if not src.is_file():
                raise ArtifactError(
                    f"{entry.path} was in the manifest and is not on disk; "
                    "refusing to write a short archive")
            size_now = src.stat().st_size
            if size_now < entry.size_bytes:
                raise ArtifactError(
                    f"{entry.path} shrank from {entry.size_bytes} to {size_now} "
                    "bytes between manifest and archive; that is truncation, "
                    "not appending, and the file cannot be trusted")
            info = tarfile.TarInfo(name=entry.path)
            info.size = size_now
            info.mtime = int(src.stat().st_mtime)
            with open(src, "rb") as fh:
                reader = _HashingLimitedReader(fh, size_now)
                tar.addfile(info, reader)
            if size_now != entry.size_bytes:
                if entry.lifecycle == "final_required":
                    raise ArtifactError(
                        f"{entry.path} is declared final_required and grew from "
                        f"{entry.size_bytes} to {size_now} bytes during "
                        "archiving; its producer is still running. A bounded "
                        "prefix is a mutable_snapshot, not a final artifact — "
                        "wait for the completion marker and quiescence, or "
                        "declare the class mutable_snapshot and accept that it "
                        "makes no completeness claim.")
                grew.append({"path": entry.path,
                             "manifest_bytes": entry.size_bytes,
                             "archived_bytes": size_now})
            entry.size_bytes = size_now
            entry.sha256 = reader.digest.hexdigest()
    if grew:
        manifest.appended_during_archive = grew
    return out_path


def verify_archive(archive_path: str | Path,
                   manifest: ArtifactManifest) -> list[str]:
    """Confirm the archive holds every manifest entry at the right size.

    Returns the problems, empty when the archive is complete. Sizes are checked
    from the tar headers rather than by extracting: this runs before teardown,
    on a box that may not have room for a second copy.
    """
    problems: list[str] = []
    try:
        with tarfile.open(archive_path, "r:*") as tar:
            members = {m.name: m for m in tar.getmembers() if m.isfile()}
    except (OSError, tarfile.TarError) as exc:
        return [f"archive unreadable: {type(exc).__name__}: {exc}"]
    for entry in manifest.entries:
        member = members.get(entry.path)
        if member is None:
            problems.append(f"missing from archive: {entry.path}")
        elif member.size != entry.size_bytes:
            problems.append(
                f"size mismatch for {entry.path}: manifest {entry.size_bytes}, "
                f"archive {member.size}")
    return problems


def verify_extracted(root: str | Path, manifest: ArtifactManifest) -> list[str]:
    """Re-hash the retrieved copies against the manifest. The local gate."""
    root = Path(root)
    problems: list[str] = []
    for entry in manifest.entries:
        p = root / entry.path
        if not p.is_file():
            problems.append(f"not retrieved: {entry.path}")
            continue
        digest = sha256_file(p)
        if digest != entry.sha256:
            problems.append(
                f"hash mismatch for {entry.path}: pod {entry.sha256[:16]}… "
                f"local {digest[:16]}…")
    return problems


# --------------------------------------------------------------------------
# The teardown gate
# --------------------------------------------------------------------------

# Ordered. Each check may only be evaluated once its predecessors hold, so the
# reported failure is the *first* thing that went wrong rather than the last
# thing noticed — E6b's report said "artifacts verified" because the digest of
# an incomplete bundle matched.
GATE_ORDER: tuple[str, ...] = (
    "training_complete",
    "evaluation_complete",
    "artifact_manifest_created",
    "required_files_present",
    # Separate from `required_files_present` on purpose. Presence is "the file
    # is here"; quiescence is "its producer has finished and it stopped
    # growing". The bounded-read archive can capture a growing log — that makes
    # it archivable, not finished — so a normal teardown asks both questions.
    "final_streams_quiescent",
    "archive_created",
    "archive_contents_verified",
    "transfer_complete",
    "local_hashes_verified",
    "checkpoint_hashes_matched",
    # Separate from `checkpoint_hashes_matched`, which is `all([])` and therefore
    # VACUOUSLY TRUE when nothing was fetched. This asks the other question: were
    # the products this session OWES off-pod actually secured? Phase-A attempt 11
    # staged five selected leaves on the pod, fetched none of them because the
    # product fetch returns early when stage 2 failed, and lost all five — with
    # every other check green.
    "required_products_secured",
    "report_inputs_verified",
)


@dataclass(frozen=True)
class GateDecision:
    allowed: bool
    emergency: bool
    failed_check: str | None
    reason: str
    checks: dict[str, bool]
    # Named event streams the session is knowingly losing the tail of. Empty on
    # every normal teardown by construction — a normal teardown cannot pass with
    # `final_streams_quiescent` false.
    incomplete_event_streams: tuple[str, ...] = ()

    def as_dict(self) -> dict:
        return asdict(self)


def evaluate_teardown(state: dict[str, bool], *, emergency_budget: bool = False,
                      emergency_reason: str = "",
                      incomplete_event_streams: tuple[str, ...] = (),
                      streams_at_risk: tuple[str, ...] | None = None) -> GateDecision:
    """May the pod be deleted?

    Normal path: every check in `GATE_ORDER` must be True. A check absent from
    `state` counts as False — an unreported check is not a passed one.

    Emergency path: the independent cost watchdog may delete a pod whose
    artifacts are incomplete, because an unbounded bill is worse than a lost
    artifact. It must say why, and the decision records which check it ran over
    so the loss is in the record rather than discovered later.

    `streams_at_risk` is the manifest's **evidence** about why quiescence
    failed, and it exists because those are three different failures wearing one
    name. `final_streams_quiescent` is false when a producer has not signalled
    completion, OR a file is still growing, OR a `final_required` class is simply
    **missing**. Only the first two are a stream whose tail is being truncated;
    the third is an artifact that was never written.

    That mattered on 2026-08-19. The bounded measurement declares no event
    streams at all. Its driver crashed before writing its one report, so
    quiescence was false for the third reason — and the emergency path demanded
    that it name the streams it was truncating, of which there were none. The
    session took the launcher-error route instead of the clean
    incomplete-collection route it should have had.

    Pass the streams the manifest says are genuinely at risk
    (`completion_marker_failures + still_being_written`) and the naming
    requirement applies only when there is something to name. Leave it `None` —
    the default — and the strict behaviour is unchanged, because a caller that
    supplies no evidence has not earned the weaker rule.
    """
    checks = {name: bool(state.get(name, False)) for name in GATE_ORDER}
    failed = next((name for name in GATE_ORDER if not checks[name]), None)

    if failed is None:
        return GateDecision(True, False, None,
                            "every teardown check passed", checks)
    if failed == "final_streams_quiescent" and not emergency_budget:
        return GateDecision(
            False, False, failed,
            "teardown blocked: a required event stream is still being written "
            "or its producer has not signalled completion. What is on disk is a "
            "mutable_snapshot — durable, but not a complete artifact — and a "
            "bounded prefix must not be accepted as the final one. Wait for the "
            "completion marker and quiescence, or take the emergency path and "
            "record the loss.", checks)
    if emergency_budget:
        if not emergency_reason.strip():
            raise ArtifactError(
                "an emergency teardown must record its reason; an unexplained "
                "override is indistinguishable from the bug it is overriding")
        incomplete = tuple(incomplete_event_streams)
        note = ""
        if not checks["final_streams_quiescent"]:
            # Is a stream actually being truncated, or did quiescence fail
            # because a final artifact is missing? `None` means the caller gave
            # no evidence, and an uninformed caller gets the strict rule.
            truncating = streams_at_risk is None or bool(streams_at_risk)
            if truncating and not incomplete:
                raise ArtifactError(
                    "an emergency teardown over a non-quiescent event stream "
                    "must name the streams it is truncating; 'the final event "
                    "stream is incomplete' has to be in the record, not "
                    "inferred from it later")
            if incomplete:
                note = (f" THE FINAL EVENT STREAM IS INCOMPLETE for "
                        f"{list(incomplete)}: only a mutable_snapshot survives "
                        f"and its tail is lost.")
            else:
                note = (" No event stream was truncated: this session declares "
                        "none, and quiescence failed because a final_required "
                        "artifact is missing rather than because a producer was "
                        "mid-write. The missing artifacts are listed above.")
        return GateDecision(
            True, True, failed,
            f"EMERGENCY budget teardown over a failed gate ({failed}): "
            f"{emergency_reason}. Artifacts for the remaining checks "
            f"{[c for c in GATE_ORDER if not checks[c]]} are LOST.{note}",
            checks, incomplete)
    return GateDecision(
        False, False, failed,
        f"teardown blocked at {failed!r}; the pod must not be deleted while a "
        "required artifact is only on it", checks)
