"""Enumerate artifacts in Python, and refuse teardown until they are safe here.

E6b lost its structured training logs to a bundling step that listed
`artifacts/audit/three_mode` and two JSON files — the set E6 needed — and never
listed `artifacts/stage3/e6b_*/train_log.jsonl`, because the launcher was derived
from E6, which did not train. `tar` bundled what it was given, exited 0, the
digest matched, the transfer verified, and the pod was deleted. Every check
passed. None of them was "is everything that had to survive actually here".

The related fragility is `$(ls -d …)` inside a nested ssh string: the glob is
expanded by the remote login shell, and when it matches nothing the substitution
is empty and `tar` silently bundles a smaller set. Three launchers still carry
that construct (E3, E4, E5 — frozen records of completed runs). It is banned
going forward, and this module is the replacement.

The design is one idea: **an explicit, declared manifest is the unit of
collection**, generated by Python that can fail loudly, and the archive is built
*from* that manifest rather than from a glob evaluated somewhere else. A path
that should exist and does not is a manifest error before any tar runs, at a
point in the session where the pod is still alive and the file can still be
found.

`evaluate_teardown` then gates deletion behind the ordered checklist. A missing
required artifact blocks normal teardown; only the independent cost watchdog may
override, and only with a recorded reason.
"""

from __future__ import annotations

import fnmatch
import json
import tarfile
from dataclasses import dataclass, asdict, field
from pathlib import Path

from .manifest import sha256_file


class ArtifactError(RuntimeError):
    """A required artifact class is missing or unusable."""


@dataclass(frozen=True)
class ArtifactSpec:
    """One declared artifact class and the paths that must satisfy it.

    `pattern` is expanded by Python's `glob`, relative to the manifest root —
    never by a remote shell inside a quoted ssh command.
    """

    artifact_class: str
    pattern: str
    required: bool = True
    min_matches: int = 1
    min_bytes: int = 1

    def as_dict(self) -> dict:
        return asdict(self)


# The classes a training session must bring home. `event_stream` is first and
# required because it is the one E6b lost, and because it is the only artifact
# here that cannot be reconstructed from anything else: checkpoints can be
# re-evaluated, generations are re-scoreable, console logs can be parsed, but a
# destroyed jsonl event stream is simply gone.
def training_session_specs(run_globs: tuple[str, ...]) -> tuple[ArtifactSpec, ...]:
    specs: list[ArtifactSpec] = []
    for g in run_globs:
        specs += [
            ArtifactSpec("event_stream", f"{g}/train_log.jsonl"),
            ArtifactSpec("run_manifest", f"{g}/run_manifest*.json"),
        ]
    return tuple(specs)


@dataclass
class ManifestEntry:
    path: str
    artifact_class: str
    size_bytes: int
    sha256: str


@dataclass
class ArtifactManifest:
    root: str
    entries: list[ManifestEntry] = field(default_factory=list)
    specs: list[dict] = field(default_factory=list)
    missing: list[dict] = field(default_factory=list)
    created_utc: str = ""

    @property
    def ok(self) -> bool:
        return not self.missing

    def paths(self) -> list[str]:
        return [e.path for e in self.entries]

    def by_class(self, artifact_class: str) -> list[ManifestEntry]:
        return [e for e in self.entries if e.artifact_class == artifact_class]

    def as_dict(self) -> dict:
        return {
            "root": self.root,
            "created_utc": self.created_utc,
            "ok": self.ok,
            "specs": self.specs,
            "entries": [asdict(e) for e in self.entries],
            "missing": self.missing,
        }

    def write(self, path: str | Path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.as_dict(), indent=2) + "\n")
        return path

    @classmethod
    def load(cls, path: str | Path) -> "ArtifactManifest":
        d = json.loads(Path(path).read_text())
        return cls(
            root=d["root"],
            entries=[ManifestEntry(**e) for e in d["entries"]],
            specs=d.get("specs", []),
            missing=d.get("missing", []),
            created_utc=d.get("created_utc", ""),
        )


def build_manifest(root: str | Path, specs: tuple[ArtifactSpec, ...], *,
                   created_utc: str = "") -> ArtifactManifest:
    """Expand every spec against the filesystem and hash what is there.

    Does not raise on a missing required artifact: it records it in `missing`
    and leaves `ok` False. The caller decides — on the pod, mid-session, with
    the files still reachable — whether to hunt for it or to accept the loss
    knowingly. Raising here would only turn a recoverable gap into a crashed
    collection step.
    """
    root = Path(root)
    manifest = ArtifactManifest(root=str(root), created_utc=created_utc,
                                specs=[s.as_dict() for s in specs])
    seen: set[str] = set()
    for spec in specs:
        matches = sorted(p for p in root.glob(spec.pattern) if p.is_file())
        usable = [p for p in matches if p.stat().st_size >= spec.min_bytes]
        if spec.required and len(usable) < spec.min_matches:
            manifest.missing.append({
                "artifact_class": spec.artifact_class,
                "pattern": spec.pattern,
                "matches": len(matches),
                "usable_matches": len(usable),
                "min_matches": spec.min_matches,
                "reason": ("no file matched the pattern" if not matches
                           else f"{len(matches) - len(usable)} match(es) below "
                                f"{spec.min_bytes} bytes"),
            })
        for p in usable:
            rel = str(p.relative_to(root))
            if rel in seen:
                continue
            seen.add(rel)
            manifest.entries.append(ManifestEntry(
                path=rel, artifact_class=spec.artifact_class,
                size_bytes=p.stat().st_size, sha256=sha256_file(p)))
    return manifest


def create_archive(manifest: ArtifactManifest, out_path: str | Path) -> Path:
    """Archive exactly the manifest's files. No globs, no shell.

    A path in the manifest that has vanished between manifest and archive is an
    error, not a silently smaller tarball — that difference is the entire E6b
    artifact loss.
    """
    root = Path(manifest.root)
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with tarfile.open(out_path, "w:gz") as tar:
        for entry in manifest.entries:
            src = root / entry.path
            if not src.is_file():
                raise ArtifactError(
                    f"{entry.path} was in the manifest and is not on disk; "
                    "refusing to write a short archive")
            tar.add(src, arcname=entry.path)
    return out_path


def verify_archive(archive_path: str | Path,
                   manifest: ArtifactManifest) -> list[str]:
    """Confirm the archive holds every manifest entry at the right size.

    Returns the problems, empty when the archive is complete. Sizes are checked
    from the tar headers rather than by extracting: this runs before teardown,
    on a box that may not have room for a second copy.
    """
    problems: list[str] = []
    try:
        with tarfile.open(archive_path, "r:*") as tar:
            members = {m.name: m for m in tar.getmembers() if m.isfile()}
    except (OSError, tarfile.TarError) as exc:
        return [f"archive unreadable: {type(exc).__name__}: {exc}"]
    for entry in manifest.entries:
        member = members.get(entry.path)
        if member is None:
            problems.append(f"missing from archive: {entry.path}")
        elif member.size != entry.size_bytes:
            problems.append(
                f"size mismatch for {entry.path}: manifest {entry.size_bytes}, "
                f"archive {member.size}")
    return problems


def verify_extracted(root: str | Path, manifest: ArtifactManifest) -> list[str]:
    """Re-hash the retrieved copies against the manifest. The local gate."""
    root = Path(root)
    problems: list[str] = []
    for entry in manifest.entries:
        p = root / entry.path
        if not p.is_file():
            problems.append(f"not retrieved: {entry.path}")
            continue
        digest = sha256_file(p)
        if digest != entry.sha256:
            problems.append(
                f"hash mismatch for {entry.path}: pod {entry.sha256[:16]}… "
                f"local {digest[:16]}…")
    return problems


# --------------------------------------------------------------------------
# The teardown gate
# --------------------------------------------------------------------------

# Ordered. Each check may only be evaluated once its predecessors hold, so the
# reported failure is the *first* thing that went wrong rather than the last
# thing noticed — E6b's report said "artifacts verified" because the digest of
# an incomplete bundle matched.
GATE_ORDER: tuple[str, ...] = (
    "training_complete",
    "evaluation_complete",
    "artifact_manifest_created",
    "required_files_present",
    "archive_created",
    "archive_contents_verified",
    "transfer_complete",
    "local_hashes_verified",
    "checkpoint_hashes_matched",
    "report_inputs_verified",
)


@dataclass(frozen=True)
class GateDecision:
    allowed: bool
    emergency: bool
    failed_check: str | None
    reason: str
    checks: dict[str, bool]

    def as_dict(self) -> dict:
        return asdict(self)


def evaluate_teardown(state: dict[str, bool], *, emergency_budget: bool = False,
                      emergency_reason: str = "") -> GateDecision:
    """May the pod be deleted?

    Normal path: every check in `GATE_ORDER` must be True. A check absent from
    `state` counts as False — an unreported check is not a passed one.

    Emergency path: the independent cost watchdog may delete a pod whose
    artifacts are incomplete, because an unbounded bill is worse than a lost
    artifact. It must say why, and the decision records which check it ran over
    so the loss is in the record rather than discovered later.
    """
    checks = {name: bool(state.get(name, False)) for name in GATE_ORDER}
    failed = next((name for name in GATE_ORDER if not checks[name]), None)

    if failed is None:
        return GateDecision(True, False, None,
                            "every teardown check passed", checks)
    if emergency_budget:
        if not emergency_reason.strip():
            raise ArtifactError(
                "an emergency teardown must record its reason; an unexplained "
                "override is indistinguishable from the bug it is overriding")
        return GateDecision(
            True, True, failed,
            f"EMERGENCY budget teardown over a failed gate ({failed}): "
            f"{emergency_reason}. Artifacts for the remaining checks "
            f"{[c for c in GATE_ORDER if not checks[c]]} are LOST.", checks)
    return GateDecision(
        False, False, failed,
        f"teardown blocked at {failed!r}; the pod must not be deleted while a "
        "required artifact is only on it", checks)
