"""Project the ownership index into per-tree `index.json` views.

The stage index (`logs/stages/index.json`, generated by `stage_attribution.py`)
is the ownership index: one row per logical owner, each carrying its
`canonical_scripts`, `canonical_path` (logs), `canonical_artifacts`,
`canonical_configs`, `canonical_data`, `canonical_docs` and `live_state`
legs. These files are PROJECTIONS of it — a reader standing in any tree
gets the same mapping without knowing where the index lives. They are regenerated by the convergence chain and own nothing.

    PYTHONPATH=src:scripts python scripts/maintenance/architecture/render_ownership_views.py --write
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]

STAGE_INDEX = "logs/stages/index.json"
VIEWS = {
    "scripts/index.json": "canonical_scripts",
    "artifacts/index.json": "canonical_artifacts",
    "configs/index.json": "canonical_configs",
    "data/index.json": "canonical_data",
    "docs/index.json": "canonical_docs",
}


TREE_OF_LEG = {
    "canonical_scripts": "scripts", "canonical_artifacts": "artifacts",
    "canonical_configs": "configs", "canonical_data": "data",
    "canonical_docs": "docs",
}


def build(tree_leg: str) -> dict:
    idx = json.loads((REPO / STAGE_INDEX).read_text())
    owners = []
    #: Stage-level owners first: a stage owns material no single experiment
    #: does (pipeline configs, datasets, stage documentation). A stage appears
    #: in a view only when its directory exists in that tree.
    tree = TREE_OF_LEG[tree_leg]
    for s in idx.get("stages", []):
        sid = s["stage_id"]
        rel = f"{tree}/stages/stage-{sid}"
        if (REPO / rel).is_dir():
            owners.append({
                "logical_id": f"stage-{sid}",
                "kind": "stage",
                "stage_id": sid,
                tree: rel,
                "logs": f"logs/stages/stage-{sid}",
            })
    for r in idx["experiments"]:
        if not r.get(tree_leg):
            continue
        owners.append({
            "logical_id": r["experiment_id"],
            "kind": r["classification"],
            "stage_id": r["stage_id"],
            "scripts": r.get("canonical_scripts"),
            "logs": r.get("canonical_path"),
            "artifacts": r.get("canonical_artifacts"),
            "configs": r.get("canonical_configs"),
            "data": r.get("canonical_data"),
            "docs": r.get("canonical_docs"),
            "live_state": r.get("live_state"),
        })
    return {
        "schema": "aadistill.ownership_view/v1",
        "_contract": (
            "a PROJECTION of logs/stages/index.json (the ownership index), "
            "filtered to owners with a presence in this tree. Regenerated by "
            "the convergence chain; edit stage_attribution.py, never this "
            "file. Old paths resolve through logs/index.json :: "
            "historical_paths.map. AUTHORIZES NOTHING."),
        "derived_from": STAGE_INDEX,
        "owners": owners,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()
    rc = 0
    for rel, leg in VIEWS.items():
        body = json.dumps(build(leg), indent=1, ensure_ascii=False) + "\n"
        out = REPO / rel
        if args.write:
            out.write_text(body)
            print(f"wrote {rel}")
        elif not (out.is_file() and out.read_text() == body):
            print(f"STALE: {rel}")
            rc = 1
    return rc


if __name__ == "__main__":
    sys.exit(main())
