"""Project the ownership index into `scripts/index.json` and `artifacts/index.json`.

The stage index (`logs/stages/index.json`, generated by `stage_attribution.py`)
is the ownership index: one row per logical owner, each carrying its
`canonical_scripts`, `canonical_path` (logs), `canonical_artifacts` and
`live_state` legs. These two files are PROJECTIONS of it — a reader standing
in `scripts/` or `artifacts/` gets the same mapping without knowing where the
index lives. They are regenerated by the convergence chain and own nothing.

    PYTHONPATH=src:scripts python scripts/maintenance/architecture/render_ownership_views.py --write
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]

STAGE_INDEX = "logs/stages/index.json"
VIEWS = {
    "scripts/index.json": "canonical_scripts",
    "artifacts/index.json": "canonical_artifacts",
}


def build(tree_leg: str) -> dict:
    idx = json.loads((REPO / STAGE_INDEX).read_text())
    owners = []
    for r in idx["experiments"]:
        if not r.get(tree_leg):
            continue
        owners.append({
            "logical_id": r["experiment_id"],
            "kind": r["classification"],
            "stage_id": r["stage_id"],
            "scripts": r.get("canonical_scripts"),
            "logs": r.get("canonical_path"),
            "artifacts": r.get("canonical_artifacts"),
            "live_state": r.get("live_state"),
        })
    return {
        "schema": "aadistill.ownership_view/v1",
        "_contract": (
            "a PROJECTION of logs/stages/index.json (the ownership index), "
            "filtered to owners with a presence in this tree. Regenerated by "
            "the convergence chain; edit stage_attribution.py, never this "
            "file. Old paths resolve through logs/index.json :: "
            "historical_paths.map. AUTHORIZES NOTHING."),
        "derived_from": STAGE_INDEX,
        "owners": owners,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()
    rc = 0
    for rel, leg in VIEWS.items():
        body = json.dumps(build(leg), indent=1, ensure_ascii=False) + "\n"
        out = REPO / rel
        if args.write:
            out.write_text(body)
            print(f"wrote {rel}")
        elif not (out.is_file() and out.read_text() == body):
            print(f"STALE: {rel}")
            rc = 1
    return rc


if __name__ == "__main__":
    sys.exit(main())
