"""E6b's whole claim is a single-variable one, so the variable is pinned here.

The experiment fills one cell of an objective × data-scale matrix, and its
conclusions are only worth anything while two sentences hold:

* against `e1_r2960k_{seed}_pca` — the same rung — **only the objective differs**;
* against `e4_p2_r1600k_{seed}` — the same objective — **only the rung differs**,
  along with the quantities a rung mechanically implies.

A confounded comparison is undetectable from the result: it looks exactly like a
real effect. So the invariant lives in a test rather than in a comment, and the
configs are generated by a script whose output these tests re-derive — editing a
generated config by hand fails here.
"""

import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "src"))

from aadistill.infrastructure.manifest import sha256_json  # noqa: E402

E6B = REPO / "configs/stage3/e6b"
SEEDS = {"sa": 20260726, "sb": 20260801}
CE_HEAVY = {"ce_weight": 1.0, "kd_weight": 0.25,
            "kd_temperature": 1.0, "kd_scope": "all"}
KD_HEAVY = {"ce_weight": 0.25, "kd_weight": 1.0,
            "kd_temperature": 1.0, "kd_scope": "all"}
ALLOWED_VS_E1 = {"loss", "run_name", "out_dir", "_purpose"}
ALLOWED_VS_P2 = {"rung", "schedule", "checkpoint", "intervals",
                 "run_name", "out_dir", "_purpose"}

pytestmark = pytest.mark.skipif(
    not (E6B / "e6b_p2_r2960k_sa.json").is_file(),
    reason="E6b configs not generated yet")


def cfg(path: Path) -> dict:
    return json.loads(path.read_text())


def diff_keys(a: dict, b: dict) -> set:
    return {k for k in set(a) | set(b)
            if json.dumps(a.get(k), sort_keys=True)
            != json.dumps(b.get(k), sort_keys=True)}


@pytest.mark.parametrize("seed", sorted(SEEDS))
def test_only_the_objective_differs_from_e1_at_the_same_rung(seed):
    a = cfg(E6B / f"e6b_p2_r2960k_{seed}.json")
    e1 = cfg(REPO / f"configs/stage3/e1/e1_r2960k_{seed}_pca.json")
    d = diff_keys(a, e1)
    assert "loss" in d, "the objective must actually differ, or there is no experiment"
    assert d <= ALLOWED_VS_E1, (
        f"E6b-{seed} differs from E1 at the same rung on {sorted(d - ALLOWED_VS_E1)}; "
        "the objective comparison would be confounded")
    assert a["loss"] == CE_HEAVY and e1["loss"] == KD_HEAVY


@pytest.mark.parametrize("seed", sorted(SEEDS))
def test_only_the_rung_differs_from_p2_at_the_lower_scale(seed):
    a = cfg(E6B / f"e6b_p2_r2960k_{seed}.json")
    p2 = cfg(REPO / f"configs/stage3/e4/e4_p2_r1600k_{seed}.json")
    d = diff_keys(a, p2)
    assert "rung" in d, "the rung must actually differ, or there is no scale arm"
    assert d <= ALLOWED_VS_P2, (
        f"E6b-{seed} differs from P2 at 1.60M on {sorted(d - ALLOWED_VS_P2)}; "
        "the scale comparison would be confounded")
    assert a["loss"] == p2["loss"], "the objective must be carried over unchanged"


@pytest.mark.parametrize("seed", sorted(SEEDS))
def test_schedule_is_taken_from_the_same_rung_arm_not_invented(seed):
    """total_steps and warmup follow from the block count, so they are copied."""
    a = cfg(E6B / f"e6b_p2_r2960k_{seed}.json")
    e1 = cfg(REPO / f"configs/stage3/e1/e1_r2960k_{seed}_pca.json")
    for key in ("schedule", "checkpoint", "intervals", "rung"):
        assert a[key] == e1[key], f"{key} must match the same-rung E1 arm exactly"
    assert a["schedule"]["total_steps"] == 2916


@pytest.mark.parametrize("seed", sorted(SEEDS))
def test_forks_from_the_stage1_init_and_not_from_p2_1600k(seed):
    a = cfg(E6B / f"e6b_p2_r2960k_{seed}.json")
    assert a["student_path"].endswith("qwen3_0p6b_init_v0/checkpoint"), (
        "continuing from P2-1.60M would make this a continuation experiment, "
        "not a scale experiment")
    assert a["seed"] == SEEDS[seed]


def test_configs_are_generated_and_regenerate_identically():
    """Hand-editing a generated config must fail, not silently persist."""
    before = {p.name: sha256_json(cfg(p)) for p in sorted(E6B.glob("e6b_*.json"))}
    subprocess.run([sys.executable, "scripts/training/build_e6b_configs.py"],
                   cwd=REPO, check=True, capture_output=True,
                   env={"PYTHONPATH": str(REPO / "src"), "PATH": "/usr/bin:/bin"})
    after = {p.name: sha256_json(cfg(p)) for p in sorted(E6B.glob("e6b_*.json"))}
    assert before == after, (
        "a tracked E6b config does not match what the generator produces; it was "
        "edited by hand, and the single-variable guarantee no longer holds")


def test_provenance_records_both_parents():
    prov = json.loads((E6B / "provenance.json").read_text())
    assert set(prov) == {"e6b_p2_r2960k_sa", "e6b_p2_r2960k_sb"}
    for name, p in prov.items():
        assert p["parents_agree_on_everything_else"] is True
        assert p["loss"] == CE_HEAVY
        assert p["e1_loss_at_same_rung"] == KD_HEAVY
        assert "e4_p2_r1600k" in p["objective_parent"]
        assert "e1_r2960k" in p["rung_parent"]
